apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carts-db-floshop-production-destination
spec:
  host: carts-db.floshop-production.svc.cluster.local
  subsets:
  - name: blue
    labels:
      deployment: carts-db-blue
  - name: green
    labels:
      deployment: carts-db-green